# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      backend-updates:
        applies-to: version-updates
        patterns: ["*"]
  - package-ecosystem: "npm"
    directory: "/internal/ui/_client"
    schedule:
      interval: "weekly"
    groups:
      client-updates:
        applies-to: version-updates
        patterns: ["*"]
