// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type PubKeyCredParam struct {
	Type string `json:"type"`
	Alg  int    `json:"alg"`
}

type Query struct {
}

type RelyingParty struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

type SuccessfulLogin struct {
	RedirectURL string `json:"redirectURL"`
}
