on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
jobs:
  test-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21.x']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - run: npm install
        working-directory: ./internal/ui/_client
      - run: make build-client
      - run: make test
      - run: make vet
