on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
jobs:
  test-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21.x', '1.22.x']
        mariadb-version: ['10.3', '11']
    env:
      ONEGATE_DB_DSN: "onegate:.test.@tcp(127.0.0.1:3306)/onegate?charset=utf8&parseTime=True"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - run: npm install
        working-directory: ./internal/ui/_client
      - run: make build-client
      - run: make migrate
      - run: make test
      - run: make vet
    services:
      db:
        image: docker.io/library/mariadb:${{ matrix.mariadb-version }}
        env:
          MARIADB_DATABASE: onegate
          POSTGRES_PASSWORD: postgres
          MARIADB_USER: onegate
          MARIADB_PASSWORD: .test.
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "1"
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306
